Using Bootstrap / Newsweek Clone page
GabrielJSuarez/Using-Boostrap pull request #3
Opened 2020-09-08 22:47 UTC by GabrielJSuarez

- Created clone of the Newsweek main page using HTML5 / CSS 3 / Bootstrap 4
- Created index.html with semantic code
- used bootstrap boilerplate to get all the functionality
- Created an external style sheet for precise styling
- No local images used
- Some Jquery functionality was required to accomplish the desired mobile layout but it was recreated cloning HTML code and using CSS to display it when necessary.

2020-09-08 23:10 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

 WOW, what project! ⭐
<img src="https://media1.giphy.com/media/OwQn9LCHFcQ5G/giphy.gif">

#### Hey @GabrielJSuarez, Is a pleasure to review such a good project! Congrats for the amazing work you already did, the project looks awesome! It breaks my heart 💔 not approve it right away, but I swear, we're almost done, there are just some minor changes that you guys have to implement to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [ ] Please implement the fixed navbar in small, medium, and large screens.
- [ ] That logo is way too big, please fix that 
#### Large screen issue:
![image](https://user-images.githubusercontent.com/56762529/92535455-9c5c1b00-f20d-11ea-9859-2f7ec3e6d6bb.png)

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/92535691-2f955080-f20e-11ea-8f5d-49ef69fed244.png)

- [ ] You're overusing (13x) the `!important` rule at your css code, please remove them.
Tip: you can use !important, but you shouldn't overuse it.

## [OPTIONAL CHANGES]
- [ ] Add a favicon to make it more similar to the original page;
- [ ] Put css files inside a css folder and then put that css folder inside that assets file that you already have.
- [ ] Put img files inside a img folder.

## Summary
✨ Your page looks amazing! 👏
✨ Well done on that descriptive commits! 🔝

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-09 01:04 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hello again @GabrielJSuarez, thanks for improving some of my required changes and my optional changes also! That's awesome 🚀! However... Looks like you forgot to implement one of my requirements 😕 (CSS repeated code and !important overuse)

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/92542296-c964f980-f21e-11ea-9e8f-202c27ebd8b5.png)

- [ ] You're still overusing (10x) the `!important` rule at your css code, please remove them.
Tip: you can use !important, but you shouldn't overuse it.


## Summary
✨ Your page looks even more amazing now! 👏🥇
✨ Well done on making the previously requested changes! 💯
✨ Thanks for implementing those optional changes also ⭐

That one was close! 😅
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif">

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-09 01:17 UTC, kevcap commented on assetts/css/style.css
> +  }
There's no need to wrap it in a media query

2020-09-09 01:18 UTC, kevincappuccino commented on assetts/css/style.css
> +}
Keep your code DRY. This same rule was already used alone.

2020-09-09 01:18 UTC, kevincappuccino commented on assetts/css/style.css
> +}
Keep your code DRY. This same rule was already used alone.

2020-09-09 01:18 UTC, kevincappuccino commented on assetts/css/style.css
> +  }
Keep your code DRY. This same rule was already used alone.

2020-09-09 02:28 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey @GabrielJSuarez, good job implementing the previously required changes, your project is looking good, however, to accomplish as the actual page, you required to do these changes, listed below:
 

## [REQUIRED CHANGES]
- [ ] As I previously requested, you have to remove all those `!important` rules from your CSS code.
![image](https://user-images.githubusercontent.com/56762529/92546584-4eeda700-f229-11ea-81fb-775a275df850.png)
I added some comments down below to help you 💪
(If you're having issues with that request, we can have **another** video call so we can figure out what's going on, for the first time we was able to solve that logo issue! 😎🔧)

- [ ] Please, in order to keep your repo professional, check the description of your commits, they should be descriptive so the other programmer can see exactly what you changed with that commit. [Check this link](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
![image](https://user-images.githubusercontent.com/56762529/92546792-ccb1b280-f229-11ea-8604-107a82efdf62.png)
([Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/))

#### You were doing great with those commits before, but that last commit doesn't look descriptive ⤵
![image](https://user-images.githubusercontent.com/56762529/92546963-2e721c80-f22a-11ea-8227-40d374642dcf.png)


## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +  border-width: 5px !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +  color: #666 !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    border: none !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    width: 40% !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    text-align: left !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    text-align: left !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    border-right: 1px solid #dee2e6 !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    width: 80% !important;
Please, remove that `!important` rule 🗑

2020-09-09 02:28 UTC, kevincappuccino commented on assetts/css/style.css
> +    width: 100% !important;
Please, remove that `!important` rule 🗑

2020-09-09 05:45 UTC, kubilaycaglayan requested changes
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job so far! You have done all the required changes!
There's one important thing before we move on :arrow_down: 

## GitHub Flow

- [ ]  Set your `master` branch as your default branch. Currently your default branch is `newsweek-Clone-Feature-Branch`. But in Microverse we are working with the `master` default branch.  :pray: 

:bulb: Probably this is a mistake you did involuntarily. Please don't forget, this might make your project invalid next time. You will learn more about default branches and different branching methodologies in the next chapters of the Microverse.
#### :question: Why it happened? 
:point_right: If `newsweek-Clone-Feature-Branch` was the first branch you have created then GitHub automatically makes it default.
#### :question: How can you fix it?
:point_right: You can easily change it from repository settings. 

### That's it. After doing the changes, you can request another review.

With all my respect... :pray:

2020-09-09 06:06 UTC, GabrielJSuarez commented
Are you for real?

El mar., 8 de septiembre de 2020 11:46 p. m., Kubilay Caglayan <
notifications@github.com> escribió:

> *@kubilaycaglayan* requested changes on this pull request.
>
> Hello Team 👋
> Status: Changes Required ♻️
>
> Great job so far! You have done all the required changes!
> There's one important thing before we move on ⬇️
> GitHub Flow
>
>    - Set your master branch as your default branch. Currently your
>    default branch is newsweek-Clone-Feature-Branch. But in Microverse we
>    are working with the master default branch. 🙏
>
> 💡 Probably this is a mistake you did involuntarily. Please don't forget,
> this might make your project invalid next time. You will learn more about
> default branches and different branching methodologies in the next chapters
> of the Microverse.
> ❓ Why it happened?
>
> 👉 If newsweek-Clone-Feature-Branch was the first branch you have created
> then GitHub automatically makes it default.
> ❓ How can you fix it?
>
> 👉 You can easily change it from repository settings.
> That's it. After doing the changes, you can request another review.
>
> With all my respect... 🙏
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GabrielJSuarez/Using-Boostrap/pull/3#pullrequestreview-484677104>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APE7SVUSNFRQCODQWFY3ZNLSE4JCHANCNFSM4RATYQHA>
> .
>

2020-09-09 13:05 UTC, kevincappuccino commented
### Thanks @kubilaycaglayan for noting that issue. 
#### Quick advice as a Microverse student and a Developer
@GabrielJSuarez ➡ Microverse is a school. That school has <strong>standards</strong> and it means that you <strong>must follow its standards</strong> in order to get your project approved. It will happen a lot in your professional life, because industries and companies like Google, Facebook, even local businesses and <strong>single clients</strong> also have tons of <strong>standards, rules, and cultures</strong>, and if you want to be part of any of them, you have to get used to it and deal with it in the most professional way always.

If you need anything, you can reach me through slack, or for technical questions/issues, you also can contact a Fulltime TSE.

With you the very best and see you at the top 🚀

Warm regards!

2020-09-09 14:26 UTC, GabrielJSuarez commented
The rule is to not work on the master branch, there's nothing about what
branch is the default branch but ok.

El mié., 9 sept. 2020 a las 8:05, Kevin Alves (<notifications@github.com>)
escribió:

> Thanks @kubilaycaglayan <https://github.com/kubilaycaglayan> for noting
> that issue. Quick advice as a Microverse student and a Developer
>
> @GabrielJSuarez <https://github.com/GabrielJSuarez> ➡ Microverse is a
> school. That school has *standards* and it means that you *must follow
> its standards* in order to get your project approved. It will happen a
> lot in your professional life, because industries and companies like
> Google, Facebook, even local businesses and *single clients* also have
> tons of *standards, rules, and cultures*, and if you want to be part of
> any of them, you have to get used to it and deal with it in the most
> professional way always.
>
> If you need anything, you can reach me through slack, or for technical
> questions/issues, you also can contact a Fulltime TSE.
>
> With you the very best and see you at the top 🚀
>
> Warm regards!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GabrielJSuarez/Using-Boostrap/pull/3#issuecomment-689549825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APE7SVT3BIFUPOSGXD5WCOTSE54SXANCNFSM4RATYQHA>
> .
>

2020-09-09 16:36 UTC, kubilaycaglayan approved these changes
Hello Team :wave: 
Status: Project Approved :green_circle: 

You are great! :blush: 

With all my respect...

2020-09-09 16:39 UTC, merged